create database ADS_EVENTOS;
use ADS_EVENTOS;
CREATE TABLE EVENTOS(
ID INT UNSIGNED NOT NULL auto_increment,
TITULO VARCHAR(90) NOT NULL,
LOCAL VARCHAR(90) NOT NULL,
DATA_INICIAL DATE,
DATA_FINAL DATE,
CATEGORIA_EVENTO VARCHAR(45) NOT NULL,
AREA_EVENTO VARCHAR(45) NOT NULL,
INSCRICOES BOOL NOT NULL,
DATA_INICIAL_INSCRICAO DATE,
DATA_FINAL_INSCRICAO DATE,
LIMITE_INSCRICOES INT,
SUBMISSAO BOOL NOT NULL,
DESCRICAO_EVENTO TEXT NOT NULL,
NOME_ORGANIZADOR VARCHAR(45) NOT NULL,
EMAIL_ORGANIZADOR VARCHAR(45) NOT NULL,
PRIMARY KEY(ID));

