SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `ADS_EVENTOS` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE ADS_EVENTOS;

-- -----------------------------------------------------
-- Table `ADS_EVENTOS`.`EVENTOS`
-- -----------------------------------------------------

CREATE  TABLE IF NOT EXISTS `ADS_EVENTOS`.`EVENTOS` (
ID_EVENTO INT UNSIGNED NOT NULL auto_increment,
TITULO VARCHAR(90) NOT NULL,
LOCAL VARCHAR(90) NOT NULL,
DATA_INICIAL DATE NOT NULL,
DATA_FINAL DATE NOT NULL,
CATEGORIA_EVENTO VARCHAR(45) NOT NULL,
AREA_EVENTO VARCHAR(45) NOT NULL,
INSCRICOES BOOL NOT NULL,
DATA_INICIAL_INSCRICAO DATE,
DATA_FINAL_INSCRICAO DATE,
LIMITE_INSCRICOES INT,
SUBMISSAO BOOL NOT NULL,
DESCRICAO_EVENTO TEXT NOT NULL,
NOME_ORGANIZADOR VARCHAR(45) NOT NULL,
EMAIL_ORGANIZADOR VARCHAR(45) NOT NULL,
PRIMARY KEY(ID_EVENTO))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;;


-- -----------------------------------------------------
-- Table `ADS_EVENTOS`.`USUARIO`
-- -----------------------------------------------------

CREATE  TABLE IF NOT EXISTS `ADS_EVENTOS`.`USUARIO` (
  `ID_USER` INT UNSIGNED NOT NULL auto_increment,
  `NOME` VARCHAR(50) NOT NULL ,
  `EMAIL` VARCHAR(8) NOT NULL ,
  `SENHA` VARCHAR(50) NOT NULL ,
  `SEXO` VARCHAR(10) NOT NULL ,
  `DATA_NASCIMENTO` DATE NOT NULL ,
  `CEP` VARCHAR(14) NOT NULL ,
  `ENDERECO` VARCHAR(30) NULL DEFAULT NULL ,
  `ESTADO` VARCHAR(2) NULL DEFAULT NULL ,
  `INSTITUICAO` VARCHAR(20) NULL DEFAULT NULL ,
  `TELEFONE1` VARCHAR(14) NOT NULL ,
  `TELEFONE2` VARCHAR(14) NULL DEFAULT NULL ,
  PRIMARY KEY (`ID_USER`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table Table `ADS_EVENTOS`.`INSCRICAO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `srv`.`reserva` (
  `ID_INSCRICAO` INT NOT NULL ,
  `ID_EVENTO` INT NOT NULL ,
  `ID_USER` INT NOT NULL ,
  `UPLOAD` DATETIME NOT NULL ,
  `id_destino` INT NULL ,
  `descricao_destino` VARCHAR(30) NULL ,
  `reserva_datetime` DATETIME NOT NULL ,
  PRIMARY KEY (`ID_INSCRICAO`) ,
  
ENGINE = InnoDB;

USE ADS_EVENTOS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
